**Morpho-phenotypic evaluation of algarrobo (_Neltuma pallida_) for the identification of superior individuals in dry forest ecosystems**

Sebastian Casas-Niño; Juan Rodrigo Baselly-Villanueva; Evelin Judith Salazar-Hinostroza; Sheyla Yanett Chumbimune-Vivanco; William Naurai; Nery Tirabante Terrones; Max Ramirez Rojas; Flavio Lozano-Isla.

---

## Manuscript

> https://docs.google.com/document/d/1HvlSOcJWlMDvkD5kOJ_3Blcq94MfhqX2_DXplWYjkyA/edit?tab=t.ecc2pbe3h01k

## Database

> https://docs.google.com/spreadsheets/d/19zJF9ti9AQhOCTenP6UqL0jA8Anl1s0r0ld-xzrR-PY/edit?gid=1347114226#gid=1347114226

---

# SciHub: research pipeline repository

project-root/
  ├── analysis.qmd          # Script with data analysis (R/Python)
  ├── article.qmd           # Script for formatting the article
  ├── design/               # Experimental design and setup
  │   ├── design.qmd            # Document with experimental setup and planning
  │   └── labels.pdf            # Labels for experimental units or field trials
  ├── files/                # Supporting files for the project
  │   ├── images/               # Raw and processed images
  │   ├── zotero/               # Zotero library (.rds)
  │   └── template.docx         # Journal article template  
  ├── manuscript/           # Core outputs of the article
  │   ├── Figures               # Figures for the manuscript (.jpg & .eps)
  │   ├── ESM                   # Electronic Supplementary Material (ESM)
  │   └── draft.docx            # Manuscript text versions
  └── README.qmd            # Article title with authors:
                                # Manuscript link (Google Docs)
                                # Database link (Google Sheets)

---